services:
  projectionlab-investment-updater:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projectionlab-investment-updater
    volumes:
      - ./accounts.yaml:/app/accounts.yaml:ro
    environment:
      #- RUN_INTERVAL_MINUTES=60 # Run every 60 minutes
      - RUN_ONCE=true
      - PL_USERNAME=foo@example.com
      - PL_PASSWORD=xxxxxxx
      - PL_API_KEY=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - PL_MFA_KEY=XXXXXXXXXXXXXXXXXXXXXXXX
      - PL_URL=https://app.projectionlab.com/login
      - PL_TIME_DELAY=10
      - CRYPTO_CACHE_DURATION=300
      - UPDATE_PROJECTIONLAB=true
